version: '3'

services:
  backend:
    build:
      context: ./Backend
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    volumes:
      - ./Backend:/app
    command: python -m app.app
    environment:
      - FLASK_ENV=development
      - DATABASE_URL=postgresql://user:password@user-db:5432/gestiondb_usuarios
      - FLASK_DEBUG=1
      - MONGO_URI=mongodb://mongo:27017/mi_basedatos
    depends_on:
      - user-db
      - mongo

  user-db:
    image: postgres
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=gestiondb_usuarios
    volumes:
      - user_postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  frontend:
    build:
      context: ./Frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./Frontend:/app
      - /app/node_modules  # para evitar volver a instalar paquetes
    environment:
      - CHOKIDAR_USEPOLLING=true
      - REACT_APP_USER_SERVICE_URL=http://backend:5000
    command: ["npm", "run", "start"]
    stdin_open: true
    tty: true

  mongo:
    image: mongo:latest
    container_name: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db



volumes:
  user_postgres_data:
  mongo_data:
