version: "3.8"

services:
  frontend:
    build:
      context: ./Frontend
    ports:
      - "3000:80"
    networks:
      - app-network

  backend:
    build:
      context: ./Backend
    ports:
      - "5000:5000"
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=adminpassword
      - POSTGRES_DB=user_db
      - MONGO_URI=mongodb://mongo:27017/logs
    depends_on:
      - postgres
      - mongo
    networks:
      - app-network

  postgres:
    image: postgres:13
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: adminpassword
      POSTGRES_DB: user_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app-network

  mongo:
    image: mongo:5.0
    volumes:
      - mongo_data:/data/db
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  postgres_data:
  mongo_data:
